In [1]:
#attention , 3.3.1

#create mini context vector 
#dot product
#softmax
#
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [2]:
query = inputs[1]
att_score_2=[0.0]*6
att_score_2 =torch.tensor( [torch.dot(x_i, query) for i,x_i in enumerate(inputs)])
#comprehension syntax

print(att_score_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [3]:
att_wt_2=torch.softmax(att_score_2,0) #dim??, softmax better than simple sum and divide, calculate for large val
torch.set_printoptions(precision=10, sci_mode=False)
print(att_wt_2)

tensor([0.1385475695, 0.2378913015, 0.2332740277, 0.1239915863, 0.1081818640,
        0.1581136137])


In [4]:
torch.zeros??

Docstring:
zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `0`, with the shape defined
by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`torch.set_default_device`). :attr:`device` will be

In [5]:
context_vec_2 = torch.zeros(3)
print(context_vec_2)

    
for i,x_i in enumerate(inputs):
    context_vec_2+= inputs[i]* att_wt_2[i]
print(context_vec_2)

    
#why same shape as query?, understand mathematical nature??  
# ,important draw out computation, rewrite and understand the correct loop versions, before torch.sum, and outer loop??

tensor([0., 0., 0.])
tensor([0.4418657124, 0.6514819860, 0.5683088303])


In [6]:
# 3.1.2
att_scores = inputs @ inputs.T
print(att_scores)


tensor([[0.9994999766, 0.9544000030, 0.9422000051, 0.4753000140, 0.4575999677,
         0.6310000420],
        [0.9544000030, 1.4950000048, 1.4754000902, 0.8434000015, 0.7070000172,
         1.0865000486],
        [0.9422000051, 1.4754000902, 1.4570000172, 0.8295999765, 0.7153999805,
         1.0605000257],
        [0.4753000140, 0.8434000015, 0.8295999765, 0.4936999977, 0.3473999798,
         0.6564999819],
        [0.4575999677, 0.7070000172, 0.7153999805, 0.3473999798, 0.6653999686,
         0.2935000062],
        [0.6310000420, 1.0865000486, 1.0605000257, 0.6564999819, 0.2935000062,
         0.9450000525]])


In [7]:
att_wts = torch.softmax(att_scores, dim=-1)
print(att_wts)

tensor([[0.2098347694, 0.2005814612, 0.1981492341, 0.1242282242, 0.1220487207,
         0.1451576650],
        [0.1385475844, 0.2378912866, 0.2332740426, 0.1239915937, 0.1081818715,
         0.1581136137],
        [0.1390075982, 0.2369214594, 0.2326019555, 0.1242044047, 0.1108002067,
         0.1564644277],
        [0.1435268819, 0.2073944211, 0.2045520246, 0.1461922377, 0.1262952536,
         0.1720391959],
        [0.1526108533, 0.1958386749, 0.1974906474, 0.1366866827, 0.1878589094,
         0.1295142919],
        [0.1384711713, 0.2183637172, 0.2127594352, 0.1420475692, 0.0988063738,
         0.1895517558]])


In [8]:
#3.3.2.3
all_context = att_wts @ inputs
print(all_context)

tensor([[0.4420594275, 0.5930986404, 0.5789891481],
        [0.4418657422, 0.6514819860, 0.5683088899],
        [0.4431275427, 0.6495946646, 0.5670731068],
        [0.4303897321, 0.6298280954, 0.5510270596],
        [0.4671017528, 0.5909928083, 0.5265965462],
        [0.4177244902, 0.6503232121, 0.5645352602]])


In [56]:
#3.4
x_2 = inputs[1] # second input element 1 x 6
d_in = inputs.shape[1] # the input embedding size, d=3
d_out = 2 # the output embedding size, d=2
print(d_in," ", d_out)
#trainable weights
torch.manual_seed(123)
#why same W_q,W_k,W_v for all, why torch.nn.Parameter??
W_q = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)
W_k = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)
W_v = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad = False)

3   2


In [10]:
# #import torch
# torch.rand(d_in,d_out)

# #WHY ARE WE PROJECTING , 
# why we need 3d to 2d, whats the gemoetric intuition and
# meaning behind this , IN [17]
q_2 = x_2 @ W_q
k_2  = x_2 @ W_k
w_2 = x_2 @ W_v
print(f"q_2 and k_2 : {q_2} , {k_2} and their shapes : {q_2.shape}, {k_2.shape}")

q_2 and k_2 : tensor([0.4306369424, 1.4550582170]) , tensor([0.4433156252, 1.1418625116]) and their shapes : torch.Size([2]), torch.Size([2])


In [11]:

keys  = inputs @ W_k
values = inputs @ W_v
print("values.shape:", values.shape)


values.shape: torch.Size([6, 2])


In [12]:
#why .dot() here and not @
att_score_22 = q_2.dot(keys[1])
print(f"score : {att_score_22} and shape: {att_score_22.shape}")
#att_scores_2 is 2nd row of attention matrix
# [1,6] =  [1,2] . [2,6] or [6,2] . [2,1]
att_scores_2 = q_2 @ keys.T
print(f"score : {att_scores_2} and shape: {att_scores_2.shape}")


score : 1.8523844480514526 and shape: torch.Size([])
score : tensor([1.2704830170, 1.8523844481, 1.8111066818, 1.0795172453, 0.5577305555,
        1.5439705849]) and shape: torch.Size([6])


In [13]:
torch.set_printoptions(precision=4)

In [14]:
#dim = -1 ?!
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(att_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])


In [51]:


context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.3061, 0.8210])


In [82]:
import torch.nn as nn
class SelfAttention_v1(SelfAttention_v2):
    def __init__(self, d_in, d_out):
       
        super().__init__(d_in, d_out, qkv_bias=False)
        # self.W_k = nn.Parameter(torch.rand(d_in,d_out))
        # self.W_q = nn.Parameter(torch.rand(d_in,d_out))
        # self.W_v = nn.Parameter(torch.rand(d_in,d_out))
        #print(f"W_k = {self.W_key}, '\n' W_q = { self.W_query },'\n' W_v = {self.W_value}")

    def forward(self,inputs):
        # self.q = inputs @ self.W_query
        # self.k = inputs @ self.W_key
        # self.v = inputs @ self.W_value
        # attn_scores = self.q @ self.k.T
        # attn_weights = torch.softmax(attn_scores / 
        #                              self.k.shape[-1]**0.5, dim=-1)
        # context_vec_2 = attn_weights @ self.v
        return super().forward(inputs)

In [83]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))


#self? super class? nn.Module super class? super().__init__()
#AttributeError: cannot assign parameters before Module.__init__() call
#TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 # (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 # (Tensor input, name dim, *, torch.dtype dtype = None) **why the fuck -1

# d_k != d_out , but keys.shape[-1]**0.5 , dim = -1

torch.Size([6, 3])
tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)


In [84]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        #print(f"W_q= {self.W_query}'\n', W_k = { self.W_key }'\n', W_v = {self.W_value }")
    def forward(self, x):
        #A = torch.eye(3, 2)
        print(x.shape)
        
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [96]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out, qkv_bias=False)
print(sa_v2(inputs))

torch.Size([6, 3])
tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


In [97]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

torch.Size([6, 3])
tensor([[-0.5337, -0.1051],
        [-0.5323, -0.1080],
        [-0.5323, -0.1079],
        [-0.5297, -0.1076],
        [-0.5311, -0.1066],
        [-0.5299, -0.1081]], grad_fn=<MmBackward0>)


In [98]:
#3.5.2 Causal Attention Mask
#attention scores vcalculation
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T  #why brackets
#normalize

attn_wts = torch.softmax(attn_scores / keys.shape[-1]**0.5,dim = -1)
print(attn_wts) #d_k ??  

tensor([[0.1921, 0.1646, 0.1652, 0.1550, 0.1721, 0.1510],
        [0.2041, 0.1659, 0.1662, 0.1496, 0.1665, 0.1477],
        [0.2036, 0.1659, 0.1662, 0.1498, 0.1664, 0.1480],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.1661, 0.1564],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.1585],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
# TypeError                                 Traceback (most recent call last)
# Cell In[87], line 3
#       1 #3.5.2 Causal Attention Mask
#       2 #attention scores vcalculation
# ----> 3 queries = sa_v2.W_query @ inputs
#       4 keys = sa_v2.W_keys @ inputs
#       5 attn_scores = queries @ keys

# TypeError: unsupported operand type(s) for @: 'Linear' and 'Tensor'

In [101]:
context_length = attn_scores.shape[0]
mask_simple =torch.tril(torch.ones(context_length,context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [103]:
masked_simple = attn_wts*mask_simple #Hadamard element wise product
print(masked_simple)

tensor([[0.1921, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2041, 0.1659, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2036, 0.1659, 0.1662, 0.0000, 0.0000, 0.0000],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.0000, 0.0000],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<MulBackward0>)


In [106]:
row_sums = masked_simple.sum(dim=-1, keepdim=True) #understand
masked_simple_norm = masked_simple / row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<DivBackward0>)
