In [49]:
#attention , 3.3.1

#create mini context vector 
#dot product
#softmax
#
import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [50]:
query = inputs[1]
att_score_2=[0.0]*6
att_score_2 =torch.tensor( [torch.dot(x_i, query) for i,x_i in enumerate(inputs)])
#comprehension syntax

print(att_score_2)

tensor([0.9544000626, 1.4950001240, 1.4754000902, 0.8434000015, 0.7070000172,
        1.0865000486])


In [51]:
att_wt_2=torch.softmax(att_score_2,0) #dim??, softmax better than simple sum and divide, calculate for large val
torch.set_printoptions(precision=10, sci_mode=False)
print(att_wt_2)

tensor([0.1385475695, 0.2378913015, 0.2332740277, 0.1239915863, 0.1081818640,
        0.1581136137])


In [52]:
torch.zeros??

Docstring:
zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `0`, with the shape defined
by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`torch.set_default_device`). :attr:`device` will be

In [56]:
context_vec_2 = torch.zeros(3)
print(context_vec_2)

    
for i,x_i in enumerate(inputs):
    context_vec_2+= inputs[i]* att_wt_2[i]
print(context_vec_2)

    
#why same shape as query?, understand mathematical nature??  
# ,important draw out computation, rewrite and understand the correct loop versions, before torch.sum, and outer loop??

tensor([0., 0., 0.])
tensor([0.4418657124, 0.6514819860, 0.5683088303])


In [63]:
# 3.1.2
att_scores = inputs @ inputs.T
print(att_scores)


tensor([[0.9994999766, 0.9544000030, 0.9422000051, 0.4753000140, 0.4575999677,
         0.6310000420],
        [0.9544000030, 1.4950000048, 1.4754000902, 0.8434000015, 0.7070000172,
         1.0865000486],
        [0.9422000051, 1.4754000902, 1.4570000172, 0.8295999765, 0.7153999805,
         1.0605000257],
        [0.4753000140, 0.8434000015, 0.8295999765, 0.4936999977, 0.3473999798,
         0.6564999819],
        [0.4575999677, 0.7070000172, 0.7153999805, 0.3473999798, 0.6653999686,
         0.2935000062],
        [0.6310000420, 1.0865000486, 1.0605000257, 0.6564999819, 0.2935000062,
         0.9450000525]])


In [64]:
att_wts = torch.softmax(att_scores, dim=-1)
print(att_wts)

tensor([[0.2098347694, 0.2005814612, 0.1981492341, 0.1242282242, 0.1220487207,
         0.1451576650],
        [0.1385475844, 0.2378912866, 0.2332740426, 0.1239915937, 0.1081818715,
         0.1581136137],
        [0.1390075982, 0.2369214594, 0.2326019555, 0.1242044047, 0.1108002067,
         0.1564644277],
        [0.1435268819, 0.2073944211, 0.2045520246, 0.1461922377, 0.1262952536,
         0.1720391959],
        [0.1526108533, 0.1958386749, 0.1974906474, 0.1366866827, 0.1878589094,
         0.1295142919],
        [0.1384711713, 0.2183637172, 0.2127594352, 0.1420475692, 0.0988063738,
         0.1895517558]])


In [65]:
#3.3.2.3
all_context = att_wts @ inputs
print(all_context)

tensor([[0.4420594275, 0.5930986404, 0.5789891481],
        [0.4418657422, 0.6514819860, 0.5683088899],
        [0.4431275427, 0.6495946646, 0.5670731068],
        [0.4303897321, 0.6298280954, 0.5510270596],
        [0.4671017528, 0.5909928083, 0.5265965462],
        [0.4177244902, 0.6503232121, 0.5645352602]])


In [ ]:
#3.4

